# ... keep your existing settings ...

[functions.ai-ask]
enabled = true
verify_jwt = true
import_map = "./functions/ai-ask/deno.json"
entrypoint = "./functions/ai-ask/index.ts"

[functions.equipment-public]
enabled = true
verify_jwt = true
import_map = "./functions/equipment-public/deno.json"
entrypoint = "./functions/equipment-public/index.ts"
